// This code was generated by the Gardens Point Parser Generator
// Copyright (c) Wayne Kelly, John Gough, QUT 2005-2014
// (see accompanying GPPGcopyright.rtf)

// GPPG version 1.5.2
// Machine:  DESKTOP-LRNG15B
// DateTime: 30.06.2020 14:01:02
// UserName: szymo
// Input file <../../kompilator.y - 30.06.2020 13:38:09>

// options: conflicts no-lines diagnose & report gplex conflicts

using System;
using System.Collections.Generic;
using System.CodeDom.Compiler;
using System.Globalization;
using System.Text;
using QUT.Gppg;

namespace MiniCompiler
{
public enum Tokens {error=2,EOF=3,Program=4,If=5,Else=6,
    While=7,Return=8,Read=9,Write=10,OpenPar=11,ClosePar=12,
    OpenBlock=13,CloseBlock=14,Semicolon=15,LogOr=16,LogAnd=17,Equal=18,
    NotEqual=19,Greater=20,GreaterOrEqual=21,Less=22,LessOrEqual=23,Assign=24,
    Plus=25,Minus=26,Multiply=27,Divide=28,BitOr=29,BitAnd=30,
    BitNot=31,LogNot=32,IntCast=33,DoubleCast=34,Eof=35,Error=36,
    IntValue=37,DoubleValue=38,BoolValue=39,Ident=40,Text=41,Int=42,
    Double=43,Bool=44};

public struct ValueType
{
public int      i_val;
public double   d_val;
public bool     b_val;
public string   s_val;
public ValType  val_type;
public OpType   op_type;
}
// Abstract base class for GPLEX scanners
[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
public abstract class ScanBase : AbstractScanner<ValueType,LexLocation> {
  private LexLocation __yylloc = new LexLocation();
  public override LexLocation yylloc { get { return __yylloc; } set { __yylloc = value; } }
  protected virtual bool yywrap() { return true; }
}

// Utility class for encapsulating token information
[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
public class ScanObj {
  public int token;
  public ValueType yylval;
  public LexLocation yylloc;
  public ScanObj( int t, ValueType val, LexLocation loc ) {
    this.token = t; this.yylval = val; this.yylloc = loc;
  }
}

[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
public class Parser: ShiftReduceParser<ValueType, LexLocation>
{
#pragma warning disable 649
  private static Dictionary<int, string> aliases;
#pragma warning restore 649
  private static Rule[] rules = new Rule[73];
  private static State[] states = new State[118];
  private static string[] nonTerms = new string[] {
      "type", "term", "const", "exp", "unaryExp", "bitExp", "mulExp", "addExp", 
      "relExp", "logExp", "bitOp", "mulOp", "addOp", "relOp", "logOp", "start", 
      "$accept", "program", "declarations", "statements", "declaration", "statement", 
      "block", "ifStatement", "whileStatement", "returnStatement", "readStatement", 
      "writeStatement", "expStatement", };

  static Parser() {
    states[0] = new State(new int[]{4,7,2,114},new int[]{-16,1,-18,3});
    states[1] = new State(new int[]{3,2});
    states[2] = new State(-1);
    states[3] = new State(new int[]{35,4,2,5});
    states[4] = new State(-2);
    states[5] = new State(new int[]{35,6});
    states[6] = new State(-4);
    states[7] = new State(new int[]{13,8});
    states[8] = new State(-7,new int[]{-19,9});
    states[9] = new State(new int[]{42,109,43,110,44,111,2,112,14,-14,13,-14,5,-14,7,-14,8,-14,9,-14,10,-14,40,-14,37,-14,38,-14,39,-14,11,-14,26,-14,31,-14,32,-14,33,-14,34,-14},new int[]{-20,10,-21,105,-1,106});
    states[10] = new State(new int[]{14,11,13,14,5,18,7,26,8,32,9,35,10,41,40,48,37,65,38,66,39,67,11,68,26,88,31,90,32,92,33,94,34,96,2,103},new int[]{-22,12,-23,13,-24,17,-25,25,-26,31,-27,34,-28,40,-29,100,-4,101,-10,51,-9,71,-8,78,-7,81,-6,84,-5,87,-2,62,-3,64});
    states[11] = new State(-6);
    states[12] = new State(-15);
    states[13] = new State(-16);
    states[14] = new State(-14,new int[]{-20,15});
    states[15] = new State(new int[]{14,16,13,14,5,18,7,26,8,32,9,35,10,41,40,48,37,65,38,66,39,67,11,68,26,88,31,90,32,92,33,94,34,96,2,103},new int[]{-22,12,-23,13,-24,17,-25,25,-26,31,-27,34,-28,40,-29,100,-4,101,-10,51,-9,71,-8,78,-7,81,-6,84,-5,87,-2,62,-3,64});
    states[16] = new State(-23);
    states[17] = new State(-17);
    states[18] = new State(new int[]{11,19});
    states[19] = new State(new int[]{40,48,37,65,38,66,39,67,11,68,26,88,31,90,32,92,33,94,34,96},new int[]{-4,20,-10,51,-9,71,-8,78,-7,81,-6,84,-5,87,-2,62,-3,64});
    states[20] = new State(new int[]{12,21});
    states[21] = new State(new int[]{13,14,5,18,7,26,8,32,9,35,10,41,40,48,37,65,38,66,39,67,11,68,26,88,31,90,32,92,33,94,34,96,2,103},new int[]{-22,22,-23,13,-24,17,-25,25,-26,31,-27,34,-28,40,-29,100,-4,101,-10,51,-9,71,-8,78,-7,81,-6,84,-5,87,-2,62,-3,64});
    states[22] = new State(new int[]{6,23,14,-24,13,-24,5,-24,7,-24,8,-24,9,-24,10,-24,40,-24,37,-24,38,-24,39,-24,11,-24,26,-24,31,-24,32,-24,33,-24,34,-24,2,-24});
    states[23] = new State(new int[]{13,14,5,18,7,26,8,32,9,35,10,41,40,48,37,65,38,66,39,67,11,68,26,88,31,90,32,92,33,94,34,96,2,103},new int[]{-22,24,-23,13,-24,17,-25,25,-26,31,-27,34,-28,40,-29,100,-4,101,-10,51,-9,71,-8,78,-7,81,-6,84,-5,87,-2,62,-3,64});
    states[24] = new State(-25);
    states[25] = new State(-18);
    states[26] = new State(new int[]{11,27});
    states[27] = new State(new int[]{40,48,37,65,38,66,39,67,11,68,26,88,31,90,32,92,33,94,34,96},new int[]{-4,28,-10,51,-9,71,-8,78,-7,81,-6,84,-5,87,-2,62,-3,64});
    states[28] = new State(new int[]{12,29});
    states[29] = new State(new int[]{13,14,5,18,7,26,8,32,9,35,10,41,40,48,37,65,38,66,39,67,11,68,26,88,31,90,32,92,33,94,34,96,2,103},new int[]{-22,30,-23,13,-24,17,-25,25,-26,31,-27,34,-28,40,-29,100,-4,101,-10,51,-9,71,-8,78,-7,81,-6,84,-5,87,-2,62,-3,64});
    states[30] = new State(-26);
    states[31] = new State(-19);
    states[32] = new State(new int[]{15,33});
    states[33] = new State(-27);
    states[34] = new State(-20);
    states[35] = new State(new int[]{40,36,2,38});
    states[36] = new State(new int[]{15,37});
    states[37] = new State(-28);
    states[38] = new State(new int[]{35,39});
    states[39] = new State(-29);
    states[40] = new State(-21);
    states[41] = new State(new int[]{41,44,2,46,40,48,37,65,38,66,39,67,11,68,26,88,31,90,32,92,33,94,34,96},new int[]{-4,42,-10,51,-9,71,-8,78,-7,81,-6,84,-5,87,-2,62,-3,64});
    states[42] = new State(new int[]{15,43});
    states[43] = new State(-30);
    states[44] = new State(new int[]{15,45});
    states[45] = new State(-31);
    states[46] = new State(new int[]{35,47});
    states[47] = new State(-32);
    states[48] = new State(new int[]{24,49,29,-67,30,-67,27,-67,28,-67,25,-67,26,-67,18,-67,19,-67,20,-67,21,-67,22,-67,23,-67,16,-67,17,-67,15,-67,12,-67});
    states[49] = new State(new int[]{40,48,37,65,38,66,39,67,11,68,26,88,31,90,32,92,33,94,34,96},new int[]{-4,50,-10,51,-9,71,-8,78,-7,81,-6,84,-5,87,-2,62,-3,64});
    states[50] = new State(-35);
    states[51] = new State(new int[]{16,98,17,99,15,-36,12,-36},new int[]{-15,52});
    states[52] = new State(new int[]{40,63,37,65,38,66,39,67,11,68,26,88,31,90,32,92,33,94,34,96},new int[]{-9,53,-8,78,-7,81,-6,84,-5,87,-2,62,-3,64});
    states[53] = new State(new int[]{18,72,19,73,20,74,21,75,22,76,23,77,16,-39,17,-39,15,-39,12,-39},new int[]{-14,54});
    states[54] = new State(new int[]{40,63,37,65,38,66,39,67,11,68,26,88,31,90,32,92,33,94,34,96},new int[]{-8,55,-7,81,-6,84,-5,87,-2,62,-3,64});
    states[55] = new State(new int[]{25,79,26,80,18,-47,19,-47,20,-47,21,-47,22,-47,23,-47,16,-47,17,-47,15,-47,12,-47},new int[]{-13,56});
    states[56] = new State(new int[]{40,63,37,65,38,66,39,67,11,68,26,88,31,90,32,92,33,94,34,96},new int[]{-7,57,-6,84,-5,87,-2,62,-3,64});
    states[57] = new State(new int[]{27,82,28,83,25,-51,26,-51,18,-51,19,-51,20,-51,21,-51,22,-51,23,-51,16,-51,17,-51,15,-51,12,-51},new int[]{-12,58});
    states[58] = new State(new int[]{40,63,37,65,38,66,39,67,11,68,26,88,31,90,32,92,33,94,34,96},new int[]{-6,59,-5,87,-2,62,-3,64});
    states[59] = new State(new int[]{29,85,30,86,27,-55,28,-55,25,-55,26,-55,18,-55,19,-55,20,-55,21,-55,22,-55,23,-55,16,-55,17,-55,15,-55,12,-55},new int[]{-11,60});
    states[60] = new State(new int[]{40,63,37,65,38,66,39,67,11,68,26,88,31,90,32,92,33,94,34,96},new int[]{-5,61,-2,62,-3,64});
    states[61] = new State(-59);
    states[62] = new State(-61);
    states[63] = new State(-67);
    states[64] = new State(-68);
    states[65] = new State(-70);
    states[66] = new State(-71);
    states[67] = new State(-72);
    states[68] = new State(new int[]{40,48,37,65,38,66,39,67,11,68,26,88,31,90,32,92,33,94,34,96},new int[]{-4,69,-10,51,-9,71,-8,78,-7,81,-6,84,-5,87,-2,62,-3,64});
    states[69] = new State(new int[]{12,70});
    states[70] = new State(-69);
    states[71] = new State(new int[]{18,72,19,73,20,74,21,75,22,76,23,77,16,-40,17,-40,15,-40,12,-40},new int[]{-14,54});
    states[72] = new State(-41);
    states[73] = new State(-42);
    states[74] = new State(-43);
    states[75] = new State(-44);
    states[76] = new State(-45);
    states[77] = new State(-46);
    states[78] = new State(new int[]{25,79,26,80,18,-48,19,-48,20,-48,21,-48,22,-48,23,-48,16,-48,17,-48,15,-48,12,-48},new int[]{-13,56});
    states[79] = new State(-49);
    states[80] = new State(-50);
    states[81] = new State(new int[]{27,82,28,83,25,-52,26,-52,18,-52,19,-52,20,-52,21,-52,22,-52,23,-52,16,-52,17,-52,15,-52,12,-52},new int[]{-12,58});
    states[82] = new State(-53);
    states[83] = new State(-54);
    states[84] = new State(new int[]{29,85,30,86,27,-56,28,-56,25,-56,26,-56,18,-56,19,-56,20,-56,21,-56,22,-56,23,-56,16,-56,17,-56,15,-56,12,-56},new int[]{-11,60});
    states[85] = new State(-57);
    states[86] = new State(-58);
    states[87] = new State(-60);
    states[88] = new State(new int[]{40,63,37,65,38,66,39,67,11,68,26,88,31,90,32,92,33,94,34,96},new int[]{-5,89,-2,62,-3,64});
    states[89] = new State(-62);
    states[90] = new State(new int[]{40,63,37,65,38,66,39,67,11,68,26,88,31,90,32,92,33,94,34,96},new int[]{-5,91,-2,62,-3,64});
    states[91] = new State(-63);
    states[92] = new State(new int[]{40,63,37,65,38,66,39,67,11,68,26,88,31,90,32,92,33,94,34,96},new int[]{-5,93,-2,62,-3,64});
    states[93] = new State(-64);
    states[94] = new State(new int[]{40,63,37,65,38,66,39,67,11,68,26,88,31,90,32,92,33,94,34,96},new int[]{-5,95,-2,62,-3,64});
    states[95] = new State(-65);
    states[96] = new State(new int[]{40,63,37,65,38,66,39,67,11,68,26,88,31,90,32,92,33,94,34,96},new int[]{-5,97,-2,62,-3,64});
    states[97] = new State(-66);
    states[98] = new State(-37);
    states[99] = new State(-38);
    states[100] = new State(-22);
    states[101] = new State(new int[]{15,102});
    states[102] = new State(-33);
    states[103] = new State(new int[]{35,104});
    states[104] = new State(-34);
    states[105] = new State(-8);
    states[106] = new State(new int[]{40,107});
    states[107] = new State(new int[]{15,108});
    states[108] = new State(-9);
    states[109] = new State(-11);
    states[110] = new State(-12);
    states[111] = new State(-13);
    states[112] = new State(new int[]{35,113});
    states[113] = new State(-10);
    states[114] = new State(new int[]{35,117,4,7},new int[]{-18,115});
    states[115] = new State(new int[]{35,116});
    states[116] = new State(-3);
    states[117] = new State(-5);

    for (int sNo = 0; sNo < states.Length; sNo++) states[sNo].number = sNo;

    rules[1] = new Rule(-17, new int[]{-16,3});
    rules[2] = new Rule(-16, new int[]{-18,35});
    rules[3] = new Rule(-16, new int[]{2,-18,35});
    rules[4] = new Rule(-16, new int[]{-18,2,35});
    rules[5] = new Rule(-16, new int[]{2,35});
    rules[6] = new Rule(-18, new int[]{4,13,-19,-20,14});
    rules[7] = new Rule(-19, new int[]{});
    rules[8] = new Rule(-19, new int[]{-19,-21});
    rules[9] = new Rule(-21, new int[]{-1,40,15});
    rules[10] = new Rule(-21, new int[]{2,35});
    rules[11] = new Rule(-1, new int[]{42});
    rules[12] = new Rule(-1, new int[]{43});
    rules[13] = new Rule(-1, new int[]{44});
    rules[14] = new Rule(-20, new int[]{});
    rules[15] = new Rule(-20, new int[]{-20,-22});
    rules[16] = new Rule(-22, new int[]{-23});
    rules[17] = new Rule(-22, new int[]{-24});
    rules[18] = new Rule(-22, new int[]{-25});
    rules[19] = new Rule(-22, new int[]{-26});
    rules[20] = new Rule(-22, new int[]{-27});
    rules[21] = new Rule(-22, new int[]{-28});
    rules[22] = new Rule(-22, new int[]{-29});
    rules[23] = new Rule(-23, new int[]{13,-20,14});
    rules[24] = new Rule(-24, new int[]{5,11,-4,12,-22});
    rules[25] = new Rule(-24, new int[]{5,11,-4,12,-22,6,-22});
    rules[26] = new Rule(-25, new int[]{7,11,-4,12,-22});
    rules[27] = new Rule(-26, new int[]{8,15});
    rules[28] = new Rule(-27, new int[]{9,40,15});
    rules[29] = new Rule(-27, new int[]{9,2,35});
    rules[30] = new Rule(-28, new int[]{10,-4,15});
    rules[31] = new Rule(-28, new int[]{10,41,15});
    rules[32] = new Rule(-28, new int[]{10,2,35});
    rules[33] = new Rule(-29, new int[]{-4,15});
    rules[34] = new Rule(-29, new int[]{2,35});
    rules[35] = new Rule(-4, new int[]{40,24,-4});
    rules[36] = new Rule(-4, new int[]{-10});
    rules[37] = new Rule(-15, new int[]{16});
    rules[38] = new Rule(-15, new int[]{17});
    rules[39] = new Rule(-10, new int[]{-10,-15,-9});
    rules[40] = new Rule(-10, new int[]{-9});
    rules[41] = new Rule(-14, new int[]{18});
    rules[42] = new Rule(-14, new int[]{19});
    rules[43] = new Rule(-14, new int[]{20});
    rules[44] = new Rule(-14, new int[]{21});
    rules[45] = new Rule(-14, new int[]{22});
    rules[46] = new Rule(-14, new int[]{23});
    rules[47] = new Rule(-9, new int[]{-9,-14,-8});
    rules[48] = new Rule(-9, new int[]{-8});
    rules[49] = new Rule(-13, new int[]{25});
    rules[50] = new Rule(-13, new int[]{26});
    rules[51] = new Rule(-8, new int[]{-8,-13,-7});
    rules[52] = new Rule(-8, new int[]{-7});
    rules[53] = new Rule(-12, new int[]{27});
    rules[54] = new Rule(-12, new int[]{28});
    rules[55] = new Rule(-7, new int[]{-7,-12,-6});
    rules[56] = new Rule(-7, new int[]{-6});
    rules[57] = new Rule(-11, new int[]{29});
    rules[58] = new Rule(-11, new int[]{30});
    rules[59] = new Rule(-6, new int[]{-6,-11,-5});
    rules[60] = new Rule(-6, new int[]{-5});
    rules[61] = new Rule(-5, new int[]{-2});
    rules[62] = new Rule(-5, new int[]{26,-5});
    rules[63] = new Rule(-5, new int[]{31,-5});
    rules[64] = new Rule(-5, new int[]{32,-5});
    rules[65] = new Rule(-5, new int[]{33,-5});
    rules[66] = new Rule(-5, new int[]{34,-5});
    rules[67] = new Rule(-2, new int[]{40});
    rules[68] = new Rule(-2, new int[]{-3});
    rules[69] = new Rule(-2, new int[]{11,-4,12});
    rules[70] = new Rule(-3, new int[]{37});
    rules[71] = new Rule(-3, new int[]{38});
    rules[72] = new Rule(-3, new int[]{39});
  }

  protected override void Initialize() {
    this.InitSpecialTokens((int)Tokens.error, (int)Tokens.EOF);
    this.InitStates(states);
    this.InitRules(rules);
    this.InitNonTerminals(nonTerms);
  }

  protected override void DoAction(int action)
  {
#pragma warning disable 162, 1522
    switch (action)
    {
      case 2: // start -> program, Eof
{
                        YYAccept();
                    }
        break;
      case 3: // start -> error, program, Eof
{
                        Compiler.AddError(new UnexpectedTokenError(1));
                        yyerrok();
                        YYAbort();
                    }
        break;
      case 4: // start -> program, error, Eof
{
                        Compiler.AddError(new UnexpectedTokenError(Compiler.GetLineNumber()-1));
                        yyerrok();
                        YYAbort();
                    }
        break;
      case 5: // start -> error, Eof
{
                        Compiler.AddError(new UnexpectedTokenError(1));
                        yyerrok();
                        YYAbort();
                    }
        break;
      case 9: // declaration -> type, Ident, Semicolon
{
                        if(Compiler.GetVariable(ValueStack[ValueStack.Depth-2].s_val) == null)
                        {
                            Compiler.DeclareVariable(ValueStack[ValueStack.Depth-3].val_type, ValueStack[ValueStack.Depth-2].s_val);
                            Compiler.AddNode(new DeclarationNode(Compiler.GetLineNumber(), ValueStack[ValueStack.Depth-3].val_type, ValueStack[ValueStack.Depth-2].s_val)); 
                        }
                        else
                        {
                            Compiler.AddError(new VariableAlreadyDeclaredError(Compiler.GetLineNumber(), ValueStack[ValueStack.Depth-2].s_val));
                        }
                    }
        break;
      case 10: // declaration -> error, Eof
{
                        Compiler.AddError(new UnexpectedTokenError(Compiler.GetLineNumber()-1));
                        yyerrok();
                        YYAbort();
                    }
        break;
      case 11: // type -> Int
{ CurrentSemanticValue.val_type = ValType.Int; }
        break;
      case 12: // type -> Double
{ CurrentSemanticValue.val_type = ValType.Double; }
        break;
      case 13: // type -> Bool
{ CurrentSemanticValue.val_type = ValType.Bool; }
        break;
      case 14: // statements -> /* empty */
{
                    Compiler.AddNode(new StatementsBlockNode(Compiler.GetLineNumber()));
                }
        break;
      case 15: // statements -> statements, statement
{
                        var innerNode = Compiler.GetNode();
                        var blockNode = Compiler.GetNode() as StatementsBlockNode;
                        if(blockNode != null)
                        {
                            blockNode.AddInnerNode(innerNode);
                            Compiler.AddNode(blockNode);
                        }
                        else
                        {
                            Compiler.AddNode(innerNode);
                        }
                    }
        break;
      case 24: // ifStatement -> If, OpenPar, exp, ClosePar, statement
{
                        if(ValueStack[ValueStack.Depth-3].val_type != ValType.Bool)
                        {
                            var error = new InvalidTypeError(Compiler.GetLineNumber()-1, ValueStack[ValueStack.Depth-3].val_type, ValType.Bool);
                            Compiler.AddError(error);
                        }
                        else
                        {
                            var thenStatement = Compiler.GetNode();
                            var condition = Compiler.GetNode();

                            Compiler.AddNode(new IfStatementNode(Compiler.GetLineNumber(), condition, thenStatement));
                        }
                    }
        break;
      case 25: // ifStatement -> If, OpenPar, exp, ClosePar, statement, Else, statement
{
                        if(ValueStack[ValueStack.Depth-5].val_type != ValType.Bool)
                        {
                            var error = new InvalidTypeError(Compiler.GetLineNumber()-1, ValueStack[ValueStack.Depth-5].val_type, ValType.Bool);
                            Compiler.AddError(error);
                        }
                        else
                        {
                            var elseStatement = Compiler.GetNode();
                            var thenStatement = Compiler.GetNode();
                            var condition = Compiler.GetNode();

                            Compiler.AddNode(new IfStatementNode(Compiler.GetLineNumber(), condition, thenStatement, elseStatement));
                        }
                    }
        break;
      case 26: // whileStatement -> While, OpenPar, exp, ClosePar, statement
{
                        //Compiler.Breakpoint();

                        if(ValueStack[ValueStack.Depth-3].val_type != ValType.Bool)
                        {
                            var error = new InvalidTypeError(Compiler.GetLineNumber()-1, ValueStack[ValueStack.Depth-3].val_type, ValType.Bool);
                            Compiler.AddError(error);
                        }
                        else
                        {
                            var thenStatement = Compiler.GetNode();
                            var condition = Compiler.GetNode();

                            Compiler.AddNode(new WhileStatementNode(Compiler.GetLineNumber(), condition, thenStatement));
                        }
                    }
        break;
      case 27: // returnStatement -> Return, Semicolon
{
                        Compiler.AddNode(new ReturnNode(Compiler.GetLineNumber()));
                    }
        break;
      case 28: // readStatement -> Read, Ident, Semicolon
{
                        if(Compiler.GetVariable(ValueStack[ValueStack.Depth-2].s_val) == null)
                        {
                            Compiler.AddError(new VariableNotDeclaredError(Compiler.GetLineNumber(), ValueStack[ValueStack.Depth-2].s_val));
                        }
                        else
                        {
                            Compiler.AddNode(new ReadNode(Compiler.GetLineNumber(), ValueStack[ValueStack.Depth-2].s_val));
                        }
                    }
        break;
      case 29: // readStatement -> Read, error, Eof
{
                        Compiler.AddError(new UnexpectedTokenError(Compiler.GetLineNumber()-1));
                        yyerrok();
                        YYAbort();
                    }
        break;
      case 30: // writeStatement -> Write, exp, Semicolon
{
                        var expNode = Compiler.GetNode();
                        Compiler.AddNode(new WriteNode(Compiler.GetLineNumber(), expNode));
                    }
        break;
      case 31: // writeStatement -> Write, Text, Semicolon
{
                        Compiler.AddNode(new WriteNode(Compiler.GetLineNumber(), ValueStack[ValueStack.Depth-2].s_val));
                    }
        break;
      case 32: // writeStatement -> Write, error, Eof
{
                        Compiler.AddError(new UnexpectedTokenError(Compiler.GetLineNumber()-1));
                        yyerrok();
                        YYAbort();
                    }
        break;
      case 33: // expStatement -> exp, Semicolon
{
                        Compiler.Pop();
                    }
        break;
      case 34: // expStatement -> error, Eof
{
                        Compiler.AddError(new UnexpectedTokenError(Compiler.GetLineNumber()));
                        yyerrok();
                        YYAbort();
                    }
        break;
      case 35: // exp -> Ident, Assign, exp
{
                        var varType = Compiler.GetVariable(ValueStack[ValueStack.Depth-3].s_val);
                        SyntaxTreeNode right;
                        if(varType == null)
                        {
                            var error = new VariableNotDeclaredError(Compiler.GetLineNumber(), ValueStack[ValueStack.Depth-3].s_val);
                            Compiler.AddError(error);

                            right = Compiler.GetNode();
                            CurrentSemanticValue.val_type = ValueStack[ValueStack.Depth-1].val_type;
                        }
                        else if(varType == ValType.Double && ValueStack[ValueStack.Depth-1].val_type == ValType.Int)
                        {
                            // Implicit cast from int to double
                            var tempNode = Compiler.GetNode();

                            CurrentSemanticValue.val_type = varType.Value;
                            right = new UnaryOperationNode(Compiler.GetLineNumber(), CurrentSemanticValue.val_type, OpType.DoubleCast, tempNode);
                        }
                        else if(varType.Value != ValueStack[ValueStack.Depth-1].val_type)
                        {
                            var error = new InvalidTypeError(Compiler.GetLineNumber(), ValueStack[ValueStack.Depth-1].val_type, varType.Value);
                            Compiler.AddError(error);

                            right = Compiler.GetNode();
                            CurrentSemanticValue.val_type = varType.Value;
                        }
                        else
                        {
                            right = Compiler.GetNode();
                            CurrentSemanticValue.val_type = ValueStack[ValueStack.Depth-1].val_type;
                        }
                        
                        Compiler.AddNode(new AssignmentNode(Compiler.GetLineNumber(), CurrentSemanticValue.val_type, ValueStack[ValueStack.Depth-3].s_val, right)); 
                    }
        break;
      case 36: // exp -> logExp
{
                        CurrentSemanticValue.val_type = ValueStack[ValueStack.Depth-1].val_type;
                    }
        break;
      case 37: // logOp -> LogOr
{ CurrentSemanticValue.op_type = OpType.LogOr; }
        break;
      case 38: // logOp -> LogAnd
{ CurrentSemanticValue.op_type = OpType.LogAnd; }
        break;
      case 39: // logExp -> logExp, logOp, relExp
{
                        if(ValueStack[ValueStack.Depth-3].val_type != ValType.Bool && ValueStack[ValueStack.Depth-3].val_type != ValType.Dynamic)
                        {
                            var error = new InvalidTypeError(Compiler.GetLineNumber(), ValueStack[ValueStack.Depth-3].val_type, ValType.Bool);
                            Compiler.AddError(error);
                        }
                        if(ValueStack[ValueStack.Depth-1].val_type != ValType.Bool && ValueStack[ValueStack.Depth-1].val_type != ValType.Dynamic)
                        {
                            var error = new InvalidTypeError(Compiler.GetLineNumber(), ValueStack[ValueStack.Depth-1].val_type, ValType.Bool);
                            Compiler.AddError(error);
                        }

                        CurrentSemanticValue.val_type = ValType.Bool;

                        var right = Compiler.GetNode();
                        var left = Compiler.GetNode();
                        Compiler.AddNode(new BinaryOperationNode(Compiler.GetLineNumber(), CurrentSemanticValue.val_type, ValueStack[ValueStack.Depth-2].op_type, left, right)); 
                    }
        break;
      case 40: // logExp -> relExp
{
                        CurrentSemanticValue.val_type = ValueStack[ValueStack.Depth-1].val_type;
                    }
        break;
      case 41: // relOp -> Equal
{ CurrentSemanticValue.op_type = OpType.Equal; }
        break;
      case 42: // relOp -> NotEqual
{ CurrentSemanticValue.op_type = OpType.NotEqual; }
        break;
      case 43: // relOp -> Greater
{ CurrentSemanticValue.op_type = OpType.Greater; }
        break;
      case 44: // relOp -> GreaterOrEqual
{ CurrentSemanticValue.op_type = OpType.GreaterOrEqual; }
        break;
      case 45: // relOp -> Less
{ CurrentSemanticValue.op_type = OpType.Less; }
        break;
      case 46: // relOp -> LessOrEqual
{ CurrentSemanticValue.op_type = OpType.LessOrEqual; }
        break;
      case 47: // relExp -> relExp, relOp, addExp
{
                        if(ValueStack[ValueStack.Depth-2].op_type != OpType.Equal && ValueStack[ValueStack.Depth-2].op_type != OpType.NotEqual)
                        {
                            if(ValueStack[ValueStack.Depth-3].val_type == ValType.Bool)
                            {
                                var error = new InvalidTypeError(Compiler.GetLineNumber(), ValueStack[ValueStack.Depth-3].val_type, ValType.Int, ValType.Double);
                                Compiler.AddError(error);
                            }
                            if(ValueStack[ValueStack.Depth-1].val_type == ValType.Bool)
                            {
                                var error = new InvalidTypeError(Compiler.GetLineNumber(), ValueStack[ValueStack.Depth-1].val_type, ValType.Int, ValType.Double);
                                Compiler.AddError(error);
                            }
                        }

                        CurrentSemanticValue.val_type = ValType.Bool;

                        var right = Compiler.GetNode();
                        var left = Compiler.GetNode();
                        Compiler.AddNode(new BinaryOperationNode(Compiler.GetLineNumber(), CurrentSemanticValue.val_type, ValueStack[ValueStack.Depth-2].op_type, left, right)); 
                    }
        break;
      case 48: // relExp -> addExp
{
                        CurrentSemanticValue.val_type = ValueStack[ValueStack.Depth-1].val_type;
                    }
        break;
      case 49: // addOp -> Plus
{ CurrentSemanticValue.op_type = OpType.Plus; }
        break;
      case 50: // addOp -> Minus
{ CurrentSemanticValue.op_type = OpType.Minus; }
        break;
      case 51: // addExp -> addExp, addOp, mulExp
{
                        var invalidType = false;
                        if(ValueStack[ValueStack.Depth-3].val_type == ValType.Bool)
                        {
                            var error = new InvalidTypeError(Compiler.GetLineNumber(), ValueStack[ValueStack.Depth-3].val_type, ValType.Int, ValType.Double);
                            Compiler.AddError(error);
                            invalidType = true;
                        }
                        if(ValueStack[ValueStack.Depth-1].val_type == ValType.Bool)
                        {
                            var error = new InvalidTypeError(Compiler.GetLineNumber(), ValueStack[ValueStack.Depth-1].val_type, ValType.Int, ValType.Double);
                            Compiler.AddError(error);
                            invalidType = true;
                        }

                        if(invalidType)
                            CurrentSemanticValue.val_type = ValType.Int;
                        else
                            CurrentSemanticValue.val_type = ValueStack[ValueStack.Depth-3].val_type == ValType.Int ? ValueStack[ValueStack.Depth-1].val_type : ValType.Double;

                        var right = Compiler.GetNode();
                        var left = Compiler.GetNode();
                        Compiler.AddNode(new BinaryOperationNode(Compiler.GetLineNumber(), CurrentSemanticValue.val_type, ValueStack[ValueStack.Depth-2].op_type, left, right)); 
                    }
        break;
      case 52: // addExp -> mulExp
{
                        CurrentSemanticValue.val_type = ValueStack[ValueStack.Depth-1].val_type;
                    }
        break;
      case 53: // mulOp -> Multiply
{ CurrentSemanticValue.op_type = OpType.Multiply; }
        break;
      case 54: // mulOp -> Divide
{ CurrentSemanticValue.op_type = OpType.Divide; }
        break;
      case 55: // mulExp -> mulExp, mulOp, bitExp
{
                        var invalidType = false;
                        if(ValueStack[ValueStack.Depth-3].val_type == ValType.Bool)
                        {
                            var error = new InvalidTypeError(Compiler.GetLineNumber(), ValueStack[ValueStack.Depth-3].val_type, ValType.Int, ValType.Double);
                            Compiler.AddError(error);
                            invalidType = true;
                        }
                        if(ValueStack[ValueStack.Depth-1].val_type == ValType.Bool)
                        {
                            var error = new InvalidTypeError(Compiler.GetLineNumber(), ValueStack[ValueStack.Depth-1].val_type, ValType.Int, ValType.Double);
                            Compiler.AddError(error);
                            invalidType = true;
                        }

                        if(invalidType)
                            CurrentSemanticValue.val_type = ValType.Int;
                        else
                            CurrentSemanticValue.val_type = ValueStack[ValueStack.Depth-3].val_type == ValType.Int ? ValueStack[ValueStack.Depth-1].val_type : ValType.Double;

                        var right = Compiler.GetNode();
                        var left = Compiler.GetNode();
                        Compiler.AddNode(new BinaryOperationNode(Compiler.GetLineNumber(), CurrentSemanticValue.val_type, ValueStack[ValueStack.Depth-2].op_type, left, right)); 
                    }
        break;
      case 56: // mulExp -> bitExp
{
                        CurrentSemanticValue.val_type = ValueStack[ValueStack.Depth-1].val_type;
                    }
        break;
      case 57: // bitOp -> BitOr
{ CurrentSemanticValue.op_type = OpType.BitOr; }
        break;
      case 58: // bitOp -> BitAnd
{ CurrentSemanticValue.op_type = OpType.BitAnd; }
        break;
      case 59: // bitExp -> bitExp, bitOp, unaryExp
{
                        if(ValueStack[ValueStack.Depth-3].val_type != ValType.Int && ValueStack[ValueStack.Depth-3].val_type != ValType.Dynamic)
                        {
                            var error = new InvalidTypeError(Compiler.GetLineNumber(), ValueStack[ValueStack.Depth-3].val_type, ValType.Int);
                            Compiler.AddError(error);
                        }
                        if(ValueStack[ValueStack.Depth-1].val_type != ValType.Int && ValueStack[ValueStack.Depth-3].val_type != ValType.Dynamic)
                        {
                            var error = new InvalidTypeError(Compiler.GetLineNumber(), ValueStack[ValueStack.Depth-1].val_type, ValType.Int);
                            Compiler.AddError(error);
                        }

                        CurrentSemanticValue.val_type = ValType.Int;
                        
                        var right = Compiler.GetNode();
                        var left = Compiler.GetNode();
                        Compiler.AddNode(new BinaryOperationNode(Compiler.GetLineNumber(), CurrentSemanticValue.val_type, ValueStack[ValueStack.Depth-2].op_type, left, right)); 
                    }
        break;
      case 60: // bitExp -> unaryExp
{
                        CurrentSemanticValue.val_type = ValueStack[ValueStack.Depth-1].val_type;
                    }
        break;
      case 61: // unaryExp -> term
{ 
                        CurrentSemanticValue.val_type = ValueStack[ValueStack.Depth-1].val_type; 
                    }
        break;
      case 62: // unaryExp -> Minus, unaryExp
{ 
                        if(ValueStack[ValueStack.Depth-1].val_type == ValType.Bool)
                        {
                            var error = new InvalidTypeError(Compiler.GetLineNumber(), ValueStack[ValueStack.Depth-1].val_type, ValType.Int, ValType.Double);
                            Compiler.AddError(error);
                        }

                        CurrentSemanticValue.val_type = ValueStack[ValueStack.Depth-1].val_type;

                        var child = Compiler.GetNode();
                        Compiler.AddNode(new UnaryOperationNode(Compiler.GetLineNumber(), CurrentSemanticValue.val_type, OpType.Minus, child)); 
                    }
        break;
      case 63: // unaryExp -> BitNot, unaryExp
{ 
                        if(ValueStack[ValueStack.Depth-1].val_type == ValType.Double || ValueStack[ValueStack.Depth-1].val_type == ValType.Bool)
                        {
                            var error = new InvalidTypeError(Compiler.GetLineNumber(), ValueStack[ValueStack.Depth-1].val_type, ValType.Int);
                            Compiler.AddError(error);
                        }

                        CurrentSemanticValue.val_type = ValueStack[ValueStack.Depth-1].val_type;

                        var child = Compiler.GetNode();
                        Compiler.AddNode(new UnaryOperationNode(Compiler.GetLineNumber(), CurrentSemanticValue.val_type, OpType.BitNot, child)); 
                    }
        break;
      case 64: // unaryExp -> LogNot, unaryExp
{
                        if(ValueStack[ValueStack.Depth-1].val_type == ValType.Int || ValueStack[ValueStack.Depth-1].val_type == ValType.Double)
                        {
                            var error = new InvalidTypeError(Compiler.GetLineNumber(), ValueStack[ValueStack.Depth-1].val_type, ValType.Bool);
                            Compiler.AddError(error);
                        }

                        CurrentSemanticValue.val_type = ValueStack[ValueStack.Depth-1].val_type;

                        var child = Compiler.GetNode();
                        Compiler.AddNode(new UnaryOperationNode(Compiler.GetLineNumber(), CurrentSemanticValue.val_type, OpType.LogNot, child)); 
                    }
        break;
      case 65: // unaryExp -> IntCast, unaryExp
{
                        CurrentSemanticValue.val_type = ValType.Int;

                        var child = Compiler.GetNode();
                        Compiler.AddNode(new UnaryOperationNode(Compiler.GetLineNumber(), CurrentSemanticValue.val_type, OpType.IntCast, child)); 
                    }
        break;
      case 66: // unaryExp -> DoubleCast, unaryExp
{
                        CurrentSemanticValue.val_type = ValType.Double;

                        var child = Compiler.GetNode();
                        Compiler.AddNode(new UnaryOperationNode(Compiler.GetLineNumber(), CurrentSemanticValue.val_type, OpType.DoubleCast, child)); 
                    }
        break;
      case 67: // term -> Ident
{
                        // Throw if variable not declared, else get ValueType
                        var varType =  Compiler.GetVariable(ValueStack[ValueStack.Depth-1].s_val);
                        if(varType == null)
                        {
                            var error = new VariableNotDeclaredError(Compiler.GetLineNumber(), ValueStack[ValueStack.Depth-1].s_val);
                            Compiler.AddError(error);

                            varType = ValType.Dynamic;
                        }

                        CurrentSemanticValue.val_type = varType.Value;
                        Compiler.AddNode(new VariableNode(Compiler.GetLineNumber(), CurrentSemanticValue.val_type, ValueStack[ValueStack.Depth-1].s_val)); 
                    }
        break;
      case 68: // term -> const
{ 
                        CurrentSemanticValue.val_type = ValueStack[ValueStack.Depth-1].val_type;
                    }
        break;
      case 69: // term -> OpenPar, exp, ClosePar
{
                        CurrentSemanticValue.val_type = ValueStack[ValueStack.Depth-2].val_type;
                    }
        break;
      case 70: // const -> IntValue
{
                        CurrentSemanticValue.val_type = ValType.Int;
                        Compiler.AddNode(new ConstantNode(Compiler.GetLineNumber(), CurrentSemanticValue.val_type, ValueStack[ValueStack.Depth-1].i_val)); 
                    }
        break;
      case 71: // const -> DoubleValue
{ 
                        CurrentSemanticValue.val_type = ValType.Double;
                        Compiler.AddNode(new ConstantNode(Compiler.GetLineNumber(), CurrentSemanticValue.val_type, ValueStack[ValueStack.Depth-1].d_val)); 
                    }
        break;
      case 72: // const -> BoolValue
{ 
                        CurrentSemanticValue.val_type = ValType.Bool;
                        Compiler.AddNode(new ConstantNode(Compiler.GetLineNumber(), CurrentSemanticValue.val_type, ValueStack[ValueStack.Depth-1].b_val)); 
                    }
        break;
    }
#pragma warning restore 162, 1522
  }

  protected override string TerminalToString(int terminal)
  {
    if (aliases != null && aliases.ContainsKey(terminal))
        return aliases[terminal];
    else if (((Tokens)terminal).ToString() != terminal.ToString(CultureInfo.InvariantCulture))
        return ((Tokens)terminal).ToString();
    else
        return CharToString((char)terminal);
  }

public Parser(Scanner scanner) : base(scanner) { }
}
}
