// This code was generated by the Gardens Point Parser Generator
// Copyright (c) Wayne Kelly, John Gough, QUT 2005-2014
// (see accompanying GPPGcopyright.rtf)

// GPPG version 1.5.2
// Machine:  DESKTOP-LRNG15B
// DateTime: 30.06.2020 20:49:23
// UserName: szymo
// Input file <../../kompilator.y - 30.06.2020 20:49:21>

// options: lines gplex

using System;
using System.Collections.Generic;
using System.CodeDom.Compiler;
using System.Globalization;
using System.Text;
using QUT.Gppg;

namespace MiniCompiler
{
public enum Tokens {error=2,EOF=3,Program=4,If=5,Else=6,
    While=7,Return=8,Read=9,Write=10,OpenPar=11,ClosePar=12,
    OpenBlock=13,CloseBlock=14,Semicolon=15,LogOr=16,LogAnd=17,Equal=18,
    NotEqual=19,Greater=20,GreaterOrEqual=21,Less=22,LessOrEqual=23,Assign=24,
    Plus=25,Minus=26,Multiply=27,Divide=28,BitOr=29,BitAnd=30,
    BitNot=31,LogNot=32,IntCast=33,DoubleCast=34,Eof=35,Error=36,
    IntValue=37,DoubleValue=38,BoolValue=39,Ident=40,Text=41,Int=42,
    Double=43,Bool=44};

public struct ValueType
#line 4 "../../kompilator.y"
{
public int      i_val;
public double   d_val;
public bool     b_val;
public string   s_val;
public ValType  val_type;
public OpType   op_type;
}
#line default
// Abstract base class for GPLEX scanners
[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
public abstract class ScanBase : AbstractScanner<ValueType,LexLocation> {
  private LexLocation __yylloc = new LexLocation();
  public override LexLocation yylloc { get { return __yylloc; } set { __yylloc = value; } }
  protected virtual bool yywrap() { return true; }
}

// Utility class for encapsulating token information
[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
public class ScanObj {
  public int token;
  public ValueType yylval;
  public LexLocation yylloc;
  public ScanObj( int t, ValueType val, LexLocation loc ) {
    this.token = t; this.yylval = val; this.yylloc = loc;
  }
}

[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
public class Parser: ShiftReduceParser<ValueType, LexLocation>
{
#pragma warning disable 649
  private static Dictionary<int, string> aliases;
#pragma warning restore 649
  private static Rule[] rules = new Rule[75];
  private static State[] states = new State[118];
  private static string[] nonTerms = new string[] {
      "type", "term", "const", "exp", "unaryExp", "bitExp", "mulExp", "addExp", 
      "relExp", "logExp", "bitOp", "mulOp", "addOp", "relOp", "logOp", "start", 
      "$accept", "program", "declarations", "statements", "declaration", "statement", 
      "block", "ifStatement", "whileStatement", "returnStatement", "readStatement", 
      "writeStatement", "expStatement", };

  static Parser() {
    states[0] = new State(new int[]{4,7,2,114},new int[]{-16,1,-18,3});
    states[1] = new State(new int[]{3,2});
    states[2] = new State(-1);
    states[3] = new State(new int[]{35,4,2,5});
    states[4] = new State(-2);
    states[5] = new State(new int[]{35,6});
    states[6] = new State(-4);
    states[7] = new State(new int[]{13,8});
    states[8] = new State(-7,new int[]{-19,9});
    states[9] = new State(new int[]{42,111,43,112,44,113,14,-13,13,-13,5,-13,7,-13,8,-13,9,-13,10,-13,40,-13,37,-13,38,-13,39,-13,11,-13,26,-13,31,-13,32,-13,2,-13},new int[]{-20,10,-21,107,-1,108});
    states[10] = new State(new int[]{14,11,13,14,5,18,7,26,8,32,9,35,10,41,40,48,37,65,38,66,39,67,11,68,26,74,31,76,32,78,2,105},new int[]{-22,12,-23,13,-24,17,-25,25,-26,31,-27,34,-28,40,-29,102,-4,103,-10,51,-9,83,-8,90,-7,93,-6,96,-5,99,-2,62,-3,64});
    states[11] = new State(-6);
    states[12] = new State(-14);
    states[13] = new State(-15);
    states[14] = new State(-13,new int[]{-20,15});
    states[15] = new State(new int[]{14,16,13,14,5,18,7,26,8,32,9,35,10,41,40,48,37,65,38,66,39,67,11,68,26,74,31,76,32,78,2,105},new int[]{-22,12,-23,13,-24,17,-25,25,-26,31,-27,34,-28,40,-29,102,-4,103,-10,51,-9,83,-8,90,-7,93,-6,96,-5,99,-2,62,-3,64});
    states[16] = new State(-22);
    states[17] = new State(-16);
    states[18] = new State(new int[]{11,19});
    states[19] = new State(new int[]{40,48,37,65,38,66,39,67,11,68,26,74,31,76,32,78},new int[]{-4,20,-10,51,-9,83,-8,90,-7,93,-6,96,-5,99,-2,62,-3,64});
    states[20] = new State(new int[]{12,21});
    states[21] = new State(new int[]{13,14,5,18,7,26,8,32,9,35,10,41,40,48,37,65,38,66,39,67,11,68,26,74,31,76,32,78,2,105},new int[]{-22,22,-23,13,-24,17,-25,25,-26,31,-27,34,-28,40,-29,102,-4,103,-10,51,-9,83,-8,90,-7,93,-6,96,-5,99,-2,62,-3,64});
    states[22] = new State(new int[]{6,23,14,-23,13,-23,5,-23,7,-23,8,-23,9,-23,10,-23,40,-23,37,-23,38,-23,39,-23,11,-23,26,-23,31,-23,32,-23,2,-23});
    states[23] = new State(new int[]{13,14,5,18,7,26,8,32,9,35,10,41,40,48,37,65,38,66,39,67,11,68,26,74,31,76,32,78,2,105},new int[]{-22,24,-23,13,-24,17,-25,25,-26,31,-27,34,-28,40,-29,102,-4,103,-10,51,-9,83,-8,90,-7,93,-6,96,-5,99,-2,62,-3,64});
    states[24] = new State(-24);
    states[25] = new State(-17);
    states[26] = new State(new int[]{11,27});
    states[27] = new State(new int[]{40,48,37,65,38,66,39,67,11,68,26,74,31,76,32,78},new int[]{-4,28,-10,51,-9,83,-8,90,-7,93,-6,96,-5,99,-2,62,-3,64});
    states[28] = new State(new int[]{12,29});
    states[29] = new State(new int[]{13,14,5,18,7,26,8,32,9,35,10,41,40,48,37,65,38,66,39,67,11,68,26,74,31,76,32,78,2,105},new int[]{-22,30,-23,13,-24,17,-25,25,-26,31,-27,34,-28,40,-29,102,-4,103,-10,51,-9,83,-8,90,-7,93,-6,96,-5,99,-2,62,-3,64});
    states[30] = new State(-25);
    states[31] = new State(-18);
    states[32] = new State(new int[]{15,33});
    states[33] = new State(-26);
    states[34] = new State(-19);
    states[35] = new State(new int[]{40,36,2,38});
    states[36] = new State(new int[]{15,37});
    states[37] = new State(-27);
    states[38] = new State(new int[]{35,39,14,-28,13,-28,5,-28,7,-28,8,-28,9,-28,10,-28,40,-28,37,-28,38,-28,39,-28,11,-28,26,-28,31,-28,32,-28,2,-28,6,-28});
    states[39] = new State(-29);
    states[40] = new State(-20);
    states[41] = new State(new int[]{41,44,2,46,40,48,37,65,38,66,39,67,11,68,26,74,31,76,32,78},new int[]{-4,42,-10,51,-9,83,-8,90,-7,93,-6,96,-5,99,-2,62,-3,64});
    states[42] = new State(new int[]{15,43});
    states[43] = new State(-30);
    states[44] = new State(new int[]{15,45});
    states[45] = new State(-31);
    states[46] = new State(new int[]{35,47,14,-32,13,-32,5,-32,7,-32,8,-32,9,-32,10,-32,40,-32,37,-32,38,-32,39,-32,11,-32,26,-32,31,-32,32,-32,2,-32,6,-32});
    states[47] = new State(-33);
    states[48] = new State(new int[]{24,49,29,-69,30,-69,27,-69,28,-69,25,-69,26,-69,18,-69,19,-69,20,-69,21,-69,22,-69,23,-69,16,-69,17,-69,15,-69,12,-69});
    states[49] = new State(new int[]{40,48,37,65,38,66,39,67,11,68,26,74,31,76,32,78},new int[]{-4,50,-10,51,-9,83,-8,90,-7,93,-6,96,-5,99,-2,62,-3,64});
    states[50] = new State(-37);
    states[51] = new State(new int[]{16,100,17,101,15,-38,12,-38},new int[]{-15,52});
    states[52] = new State(new int[]{40,63,37,65,38,66,39,67,11,68,26,74,31,76,32,78},new int[]{-9,53,-8,90,-7,93,-6,96,-5,99,-2,62,-3,64});
    states[53] = new State(new int[]{18,84,19,85,20,86,21,87,22,88,23,89,16,-41,17,-41,15,-41,12,-41},new int[]{-14,54});
    states[54] = new State(new int[]{40,63,37,65,38,66,39,67,11,68,26,74,31,76,32,78},new int[]{-8,55,-7,93,-6,96,-5,99,-2,62,-3,64});
    states[55] = new State(new int[]{25,91,26,92,18,-49,19,-49,20,-49,21,-49,22,-49,23,-49,16,-49,17,-49,15,-49,12,-49},new int[]{-13,56});
    states[56] = new State(new int[]{40,63,37,65,38,66,39,67,11,68,26,74,31,76,32,78},new int[]{-7,57,-6,96,-5,99,-2,62,-3,64});
    states[57] = new State(new int[]{27,94,28,95,25,-53,26,-53,18,-53,19,-53,20,-53,21,-53,22,-53,23,-53,16,-53,17,-53,15,-53,12,-53},new int[]{-12,58});
    states[58] = new State(new int[]{40,63,37,65,38,66,39,67,11,68,26,74,31,76,32,78},new int[]{-6,59,-5,99,-2,62,-3,64});
    states[59] = new State(new int[]{29,97,30,98,27,-57,28,-57,25,-57,26,-57,18,-57,19,-57,20,-57,21,-57,22,-57,23,-57,16,-57,17,-57,15,-57,12,-57},new int[]{-11,60});
    states[60] = new State(new int[]{40,63,37,65,38,66,39,67,11,68,26,74,31,76,32,78},new int[]{-5,61,-2,62,-3,64});
    states[61] = new State(-61);
    states[62] = new State(-63);
    states[63] = new State(-69);
    states[64] = new State(-70);
    states[65] = new State(-72);
    states[66] = new State(-73);
    states[67] = new State(-74);
    states[68] = new State(new int[]{42,71,43,80,40,48,37,65,38,66,39,67,11,68,26,74,31,76,32,78},new int[]{-4,69,-10,51,-9,83,-8,90,-7,93,-6,96,-5,99,-2,62,-3,64});
    states[69] = new State(new int[]{12,70});
    states[70] = new State(-71);
    states[71] = new State(new int[]{12,72});
    states[72] = new State(new int[]{40,63,37,65,38,66,39,67,11,68,26,74,31,76,32,78},new int[]{-5,73,-2,62,-3,64});
    states[73] = new State(-67);
    states[74] = new State(new int[]{40,63,37,65,38,66,39,67,11,68,26,74,31,76,32,78},new int[]{-5,75,-2,62,-3,64});
    states[75] = new State(-64);
    states[76] = new State(new int[]{40,63,37,65,38,66,39,67,11,68,26,74,31,76,32,78},new int[]{-5,77,-2,62,-3,64});
    states[77] = new State(-65);
    states[78] = new State(new int[]{40,63,37,65,38,66,39,67,11,68,26,74,31,76,32,78},new int[]{-5,79,-2,62,-3,64});
    states[79] = new State(-66);
    states[80] = new State(new int[]{12,81});
    states[81] = new State(new int[]{40,63,37,65,38,66,39,67,11,68,26,74,31,76,32,78},new int[]{-5,82,-2,62,-3,64});
    states[82] = new State(-68);
    states[83] = new State(new int[]{18,84,19,85,20,86,21,87,22,88,23,89,16,-42,17,-42,15,-42,12,-42},new int[]{-14,54});
    states[84] = new State(-43);
    states[85] = new State(-44);
    states[86] = new State(-45);
    states[87] = new State(-46);
    states[88] = new State(-47);
    states[89] = new State(-48);
    states[90] = new State(new int[]{25,91,26,92,18,-50,19,-50,20,-50,21,-50,22,-50,23,-50,16,-50,17,-50,15,-50,12,-50},new int[]{-13,56});
    states[91] = new State(-51);
    states[92] = new State(-52);
    states[93] = new State(new int[]{27,94,28,95,25,-54,26,-54,18,-54,19,-54,20,-54,21,-54,22,-54,23,-54,16,-54,17,-54,15,-54,12,-54},new int[]{-12,58});
    states[94] = new State(-55);
    states[95] = new State(-56);
    states[96] = new State(new int[]{29,97,30,98,27,-58,28,-58,25,-58,26,-58,18,-58,19,-58,20,-58,21,-58,22,-58,23,-58,16,-58,17,-58,15,-58,12,-58},new int[]{-11,60});
    states[97] = new State(-59);
    states[98] = new State(-60);
    states[99] = new State(-62);
    states[100] = new State(-39);
    states[101] = new State(-40);
    states[102] = new State(-21);
    states[103] = new State(new int[]{15,104});
    states[104] = new State(-34);
    states[105] = new State(new int[]{35,106,14,-35,13,-35,5,-35,7,-35,8,-35,9,-35,10,-35,40,-35,37,-35,38,-35,39,-35,11,-35,26,-35,31,-35,32,-35,2,-35,6,-35});
    states[106] = new State(-36);
    states[107] = new State(-8);
    states[108] = new State(new int[]{40,109});
    states[109] = new State(new int[]{15,110});
    states[110] = new State(-9);
    states[111] = new State(-10);
    states[112] = new State(-11);
    states[113] = new State(-12);
    states[114] = new State(new int[]{35,117,4,7},new int[]{-18,115});
    states[115] = new State(new int[]{35,116});
    states[116] = new State(-3);
    states[117] = new State(-5);

    for (int sNo = 0; sNo < states.Length; sNo++) states[sNo].number = sNo;

    rules[1] = new Rule(-17, new int[]{-16,3});
    rules[2] = new Rule(-16, new int[]{-18,35});
    rules[3] = new Rule(-16, new int[]{2,-18,35});
    rules[4] = new Rule(-16, new int[]{-18,2,35});
    rules[5] = new Rule(-16, new int[]{2,35});
    rules[6] = new Rule(-18, new int[]{4,13,-19,-20,14});
    rules[7] = new Rule(-19, new int[]{});
    rules[8] = new Rule(-19, new int[]{-19,-21});
    rules[9] = new Rule(-21, new int[]{-1,40,15});
    rules[10] = new Rule(-1, new int[]{42});
    rules[11] = new Rule(-1, new int[]{43});
    rules[12] = new Rule(-1, new int[]{44});
    rules[13] = new Rule(-20, new int[]{});
    rules[14] = new Rule(-20, new int[]{-20,-22});
    rules[15] = new Rule(-22, new int[]{-23});
    rules[16] = new Rule(-22, new int[]{-24});
    rules[17] = new Rule(-22, new int[]{-25});
    rules[18] = new Rule(-22, new int[]{-26});
    rules[19] = new Rule(-22, new int[]{-27});
    rules[20] = new Rule(-22, new int[]{-28});
    rules[21] = new Rule(-22, new int[]{-29});
    rules[22] = new Rule(-23, new int[]{13,-20,14});
    rules[23] = new Rule(-24, new int[]{5,11,-4,12,-22});
    rules[24] = new Rule(-24, new int[]{5,11,-4,12,-22,6,-22});
    rules[25] = new Rule(-25, new int[]{7,11,-4,12,-22});
    rules[26] = new Rule(-26, new int[]{8,15});
    rules[27] = new Rule(-27, new int[]{9,40,15});
    rules[28] = new Rule(-27, new int[]{9,2});
    rules[29] = new Rule(-27, new int[]{9,2,35});
    rules[30] = new Rule(-28, new int[]{10,-4,15});
    rules[31] = new Rule(-28, new int[]{10,41,15});
    rules[32] = new Rule(-28, new int[]{10,2});
    rules[33] = new Rule(-28, new int[]{10,2,35});
    rules[34] = new Rule(-29, new int[]{-4,15});
    rules[35] = new Rule(-29, new int[]{2});
    rules[36] = new Rule(-29, new int[]{2,35});
    rules[37] = new Rule(-4, new int[]{40,24,-4});
    rules[38] = new Rule(-4, new int[]{-10});
    rules[39] = new Rule(-15, new int[]{16});
    rules[40] = new Rule(-15, new int[]{17});
    rules[41] = new Rule(-10, new int[]{-10,-15,-9});
    rules[42] = new Rule(-10, new int[]{-9});
    rules[43] = new Rule(-14, new int[]{18});
    rules[44] = new Rule(-14, new int[]{19});
    rules[45] = new Rule(-14, new int[]{20});
    rules[46] = new Rule(-14, new int[]{21});
    rules[47] = new Rule(-14, new int[]{22});
    rules[48] = new Rule(-14, new int[]{23});
    rules[49] = new Rule(-9, new int[]{-9,-14,-8});
    rules[50] = new Rule(-9, new int[]{-8});
    rules[51] = new Rule(-13, new int[]{25});
    rules[52] = new Rule(-13, new int[]{26});
    rules[53] = new Rule(-8, new int[]{-8,-13,-7});
    rules[54] = new Rule(-8, new int[]{-7});
    rules[55] = new Rule(-12, new int[]{27});
    rules[56] = new Rule(-12, new int[]{28});
    rules[57] = new Rule(-7, new int[]{-7,-12,-6});
    rules[58] = new Rule(-7, new int[]{-6});
    rules[59] = new Rule(-11, new int[]{29});
    rules[60] = new Rule(-11, new int[]{30});
    rules[61] = new Rule(-6, new int[]{-6,-11,-5});
    rules[62] = new Rule(-6, new int[]{-5});
    rules[63] = new Rule(-5, new int[]{-2});
    rules[64] = new Rule(-5, new int[]{26,-5});
    rules[65] = new Rule(-5, new int[]{31,-5});
    rules[66] = new Rule(-5, new int[]{32,-5});
    rules[67] = new Rule(-5, new int[]{11,42,12,-5});
    rules[68] = new Rule(-5, new int[]{11,43,12,-5});
    rules[69] = new Rule(-2, new int[]{40});
    rules[70] = new Rule(-2, new int[]{-3});
    rules[71] = new Rule(-2, new int[]{11,-4,12});
    rules[72] = new Rule(-3, new int[]{37});
    rules[73] = new Rule(-3, new int[]{38});
    rules[74] = new Rule(-3, new int[]{39});
  }

  protected override void Initialize() {
    this.InitSpecialTokens((int)Tokens.error, (int)Tokens.EOF);
    this.InitStates(states);
    this.InitRules(rules);
    this.InitNonTerminals(nonTerms);
  }

  protected override void DoAction(int action)
  {
#pragma warning disable 162, 1522
    switch (action)
    {
      case 2: // start -> program, Eof
#line 31 "../../kompilator.y"
                    {
                        YYAccept();
                    }
#line default
        break;
      case 3: // start -> error, program, Eof
#line 35 "../../kompilator.y"
                    {
                        Compiler.AddError(new UnexpectedTokenError(1));
                        yyerrok();
                        YYAbort();
                    }
#line default
        break;
      case 4: // start -> program, error, Eof
#line 41 "../../kompilator.y"
                    {
                        Compiler.AddError(new UnexpectedTokenError(Compiler.GetLineNumber()));
                        yyerrok();
                        YYAbort();
                    }
#line default
        break;
      case 5: // start -> error, Eof
#line 47 "../../kompilator.y"
                    {
                        Compiler.AddError(new UnexpectedTokenError(Compiler.GetLineNumber()));
                        yyerrok();
                        YYAbort();
                    }
#line default
        break;
      case 9: // declaration -> type, Ident, Semicolon
#line 62 "../../kompilator.y"
                    {
                        if(Compiler.GetVariable(ValueStack[ValueStack.Depth-2].s_val) == null)
                        {
                            Compiler.DeclareVariable(ValueStack[ValueStack.Depth-3].val_type, ValueStack[ValueStack.Depth-2].s_val);
                            Compiler.AddNode(new DeclarationNode(Compiler.GetLineNumber(), ValueStack[ValueStack.Depth-3].val_type, ValueStack[ValueStack.Depth-2].s_val)); 
                        }
                        else
                        {
                            Compiler.AddError(new VariableAlreadyDeclaredError(Compiler.GetLineNumber(), ValueStack[ValueStack.Depth-2].s_val));
                        }
                    }
#line default
        break;
      case 10: // type -> Int
#line 75 "../../kompilator.y"
                                    { CurrentSemanticValue.val_type = ValType.Int; }
#line default
        break;
      case 11: // type -> Double
#line 76 "../../kompilator.y"
                                    { CurrentSemanticValue.val_type = ValType.Double; }
#line default
        break;
      case 12: // type -> Bool
#line 77 "../../kompilator.y"
                                    { CurrentSemanticValue.val_type = ValType.Bool; }
#line default
        break;
      case 13: // statements -> /* empty */
#line 81 "../../kompilator.y"
                {
                    Compiler.AddNode(new StatementsBlockNode(Compiler.GetLineNumber()));
                }
#line default
        break;
      case 14: // statements -> statements, statement
#line 85 "../../kompilator.y"
                    {
                        var innerNode = Compiler.GetNode();
                        var blockNode = Compiler.GetNode() as StatementsBlockNode;
                        if(blockNode != null)
                        {
                            blockNode.AddInnerNode(innerNode);
                            Compiler.AddNode(blockNode);
                        }
                        else
                        {
                            Compiler.AddNode(innerNode);
                        }
                    }
#line default
        break;
      case 23: // ifStatement -> If, OpenPar, exp, ClosePar, statement
#line 113 "../../kompilator.y"
                    {
                        if(ValueStack[ValueStack.Depth-3].val_type != ValType.Bool)
                        {
                            var error = new InvalidTypeError(Compiler.GetLineNumber()-1, ValueStack[ValueStack.Depth-3].val_type, ValType.Bool);
                            Compiler.AddError(error);
                        }
                        else
                        {
                            var thenStatement = Compiler.GetNode();
                            var condition = Compiler.GetNode();

                            Compiler.AddNode(new IfStatementNode(Compiler.GetLineNumber(), condition, thenStatement));
                        }
                    }
#line default
        break;
      case 24: // ifStatement -> If, OpenPar, exp, ClosePar, statement, Else, statement
#line 128 "../../kompilator.y"
                    {
                        if(ValueStack[ValueStack.Depth-5].val_type != ValType.Bool)
                        {
                            var error = new InvalidTypeError(Compiler.GetLineNumber(), ValueStack[ValueStack.Depth-5].val_type, ValType.Bool);
                            Compiler.AddError(error);
                        }
                        else
                        {
                            var elseStatement = Compiler.GetNode();
                            var thenStatement = Compiler.GetNode();
                            var condition = Compiler.GetNode();

                            Compiler.AddNode(new IfStatementNode(Compiler.GetLineNumber(), condition, thenStatement, elseStatement));
                        }
                    }
#line default
        break;
      case 25: // whileStatement -> While, OpenPar, exp, ClosePar, statement
#line 146 "../../kompilator.y"
                    {
                        if(ValueStack[ValueStack.Depth-3].val_type != ValType.Bool)
                        {
                            var error = new InvalidTypeError(Compiler.GetLineNumber(), ValueStack[ValueStack.Depth-3].val_type, ValType.Bool);
                            Compiler.AddError(error);
                        }
                        else
                        {
                            var thenStatement = Compiler.GetNode();
                            var condition = Compiler.GetNode();

                            Compiler.AddNode(new WhileStatementNode(Compiler.GetLineNumber(), condition, thenStatement));
                        }
                    }
#line default
        break;
      case 26: // returnStatement -> Return, Semicolon
#line 163 "../../kompilator.y"
                    {
                        Compiler.AddNode(new ReturnNode(Compiler.GetLineNumber()));
                    }
#line default
        break;
      case 27: // readStatement -> Read, Ident, Semicolon
#line 169 "../../kompilator.y"
                    {
                        if(Compiler.GetVariable(ValueStack[ValueStack.Depth-2].s_val) == null)
                        {
                            Compiler.AddError(new VariableNotDeclaredError(Compiler.GetLineNumber(), ValueStack[ValueStack.Depth-2].s_val));
                        }
                        else
                        {
                            Compiler.AddNode(new ReadNode(Compiler.GetLineNumber(), ValueStack[ValueStack.Depth-2].s_val));
                        }
                    }
#line default
        break;
      case 28: // readStatement -> Read, error
#line 180 "../../kompilator.y"
                    {
                        Compiler.AddError(new UnexpectedTokenError(Compiler.GetLineNumber()));
                        yyerrok();
                        yyclearin();
                    }
#line default
        break;
      case 29: // readStatement -> Read, error, Eof
#line 186 "../../kompilator.y"
                    {
                        Compiler.AddError(new UnexpectedTokenError(Compiler.GetLineNumber()));
                        yyerrok();
                        YYAbort();
                    }
#line default
        break;
      case 30: // writeStatement -> Write, exp, Semicolon
#line 194 "../../kompilator.y"
                    {
                        var expNode = Compiler.GetNode();
                        Compiler.AddNode(new WriteNode(Compiler.GetLineNumber(), expNode));
                    }
#line default
        break;
      case 31: // writeStatement -> Write, Text, Semicolon
#line 199 "../../kompilator.y"
                    {
                        Compiler.AddNode(new WriteNode(Compiler.GetLineNumber(), ValueStack[ValueStack.Depth-2].s_val));
                    }
#line default
        break;
      case 32: // writeStatement -> Write, error
#line 203 "../../kompilator.y"
                    {
                        Compiler.AddError(new UnexpectedTokenError(Compiler.GetLineNumber()));
                        yyerrok();
                        yyclearin();
                    }
#line default
        break;
      case 33: // writeStatement -> Write, error, Eof
#line 209 "../../kompilator.y"
                    {
                        Compiler.AddError(new UnexpectedTokenError(Compiler.GetLineNumber()));  
                        yyerrok();                        
                        YYAbort();
                    }
#line default
        break;
      case 34: // expStatement -> exp, Semicolon
#line 217 "../../kompilator.y"
                    {
                        Compiler.Pop();
                    }
#line default
        break;
      case 35: // expStatement -> error
#line 221 "../../kompilator.y"
                    {
                        Compiler.AddError(new UnexpectedTokenError(Compiler.GetLineNumber()));  
                        yyerrok();
                        yyclearin();
                    }
#line default
        break;
      case 36: // expStatement -> error, Eof
#line 227 "../../kompilator.y"
                    {
                        Compiler.AddError(new UnexpectedTokenError(Compiler.GetLineNumber()));  
                        yyerrok();
                        YYAbort();
                    }
#line default
        break;
      case 37: // exp -> Ident, Assign, exp
#line 235 "../../kompilator.y"
                    {
                        var varType = Compiler.GetVariable(ValueStack[ValueStack.Depth-3].s_val);
                        SyntaxTreeNode right;
                        if(varType == null)
                        {
                            var error = new VariableNotDeclaredError(Compiler.GetLineNumber(), ValueStack[ValueStack.Depth-3].s_val);
                            Compiler.AddError(error);

                            right = Compiler.GetNode();
                            CurrentSemanticValue.val_type = ValueStack[ValueStack.Depth-1].val_type;
                        }
                        else if(varType == ValType.Double && ValueStack[ValueStack.Depth-1].val_type == ValType.Int)
                        {
                            // Implicit cast from int to double
                            var tempNode = Compiler.GetNode();

                            CurrentSemanticValue.val_type = varType.Value;
                            right = new UnaryOperationNode(Compiler.GetLineNumber(), CurrentSemanticValue.val_type, OpType.DoubleCast, tempNode);
                        }
                        else if(varType.Value != ValueStack[ValueStack.Depth-1].val_type)
                        {
                            var error = new InvalidTypeError(Compiler.GetLineNumber(), ValueStack[ValueStack.Depth-1].val_type, varType.Value);
                            Compiler.AddError(error);

                            right = Compiler.GetNode();
                            CurrentSemanticValue.val_type = varType.Value;
                        }
                        else
                        {
                            right = Compiler.GetNode();
                            CurrentSemanticValue.val_type = ValueStack[ValueStack.Depth-1].val_type;
                        }
                        
                        Compiler.AddNode(new AssignmentNode(Compiler.GetLineNumber(), CurrentSemanticValue.val_type, ValueStack[ValueStack.Depth-3].s_val, right)); 
                    }
#line default
        break;
      case 38: // exp -> logExp
#line 271 "../../kompilator.y"
                    {
                        CurrentSemanticValue.val_type = ValueStack[ValueStack.Depth-1].val_type;
                    }
#line default
        break;
      case 39: // logOp -> LogOr
#line 276 "../../kompilator.y"
                                    { CurrentSemanticValue.op_type = OpType.LogOr; }
#line default
        break;
      case 40: // logOp -> LogAnd
#line 277 "../../kompilator.y"
                                    { CurrentSemanticValue.op_type = OpType.LogAnd; }
#line default
        break;
      case 41: // logExp -> logExp, logOp, relExp
#line 281 "../../kompilator.y"
                    {
                        if(ValueStack[ValueStack.Depth-3].val_type != ValType.Bool && ValueStack[ValueStack.Depth-3].val_type != ValType.Dynamic)
                        {
                            var error = new InvalidTypeError(Compiler.GetLineNumber(), ValueStack[ValueStack.Depth-3].val_type, ValType.Bool);
                            Compiler.AddError(error);
                        }
                        if(ValueStack[ValueStack.Depth-1].val_type != ValType.Bool && ValueStack[ValueStack.Depth-1].val_type != ValType.Dynamic)
                        {
                            var error = new InvalidTypeError(Compiler.GetLineNumber(), ValueStack[ValueStack.Depth-1].val_type, ValType.Bool);
                            Compiler.AddError(error);
                        }

                        CurrentSemanticValue.val_type = ValType.Bool;

                        var right = Compiler.GetNode();
                        var left = Compiler.GetNode();
                        Compiler.AddNode(new BinaryOperationNode(Compiler.GetLineNumber(), CurrentSemanticValue.val_type, ValueStack[ValueStack.Depth-2].op_type, left, right)); 
                    }
#line default
        break;
      case 42: // logExp -> relExp
#line 300 "../../kompilator.y"
                    {
                        CurrentSemanticValue.val_type = ValueStack[ValueStack.Depth-1].val_type;
                    }
#line default
        break;
      case 43: // relOp -> Equal
#line 305 "../../kompilator.y"
                                    { CurrentSemanticValue.op_type = OpType.Equal; }
#line default
        break;
      case 44: // relOp -> NotEqual
#line 306 "../../kompilator.y"
                                    { CurrentSemanticValue.op_type = OpType.NotEqual; }
#line default
        break;
      case 45: // relOp -> Greater
#line 307 "../../kompilator.y"
                                    { CurrentSemanticValue.op_type = OpType.Greater; }
#line default
        break;
      case 46: // relOp -> GreaterOrEqual
#line 308 "../../kompilator.y"
                                    { CurrentSemanticValue.op_type = OpType.GreaterOrEqual; }
#line default
        break;
      case 47: // relOp -> Less
#line 309 "../../kompilator.y"
                                    { CurrentSemanticValue.op_type = OpType.Less; }
#line default
        break;
      case 48: // relOp -> LessOrEqual
#line 310 "../../kompilator.y"
                                    { CurrentSemanticValue.op_type = OpType.LessOrEqual; }
#line default
        break;
      case 49: // relExp -> relExp, relOp, addExp
#line 314 "../../kompilator.y"
                    {
                        SyntaxTreeNode left;
                        SyntaxTreeNode right;
                        var invalidType = false;

                        // Allow bools
                        if(ValueStack[ValueStack.Depth-3].val_type == ValType.Bool || ValueStack[ValueStack.Depth-1].val_type == ValType.Bool)
                        {                          
                            // But only if comparing equality
                            if(ValueStack[ValueStack.Depth-2].op_type != OpType.Equal && ValueStack[ValueStack.Depth-2].op_type != OpType.NotEqual)
                            {
                                if(ValueStack[ValueStack.Depth-3].val_type == ValType.Bool && ValueStack[ValueStack.Depth-1].val_type != ValType.Bool)
                                {
                                    Compiler.AddError(new InvalidTypeError(Compiler.GetLineNumber(), ValueStack[ValueStack.Depth-3].val_type, ValueStack[ValueStack.Depth-1].val_type));
                                    invalidType = true;
                                }
                                else if(ValueStack[ValueStack.Depth-3].val_type != ValType.Bool && ValueStack[ValueStack.Depth-1].val_type == ValType.Bool)
                                {
                                    Compiler.AddError(new InvalidTypeError(Compiler.GetLineNumber(), ValueStack[ValueStack.Depth-1].val_type, ValueStack[ValueStack.Depth-3].val_type));
                                    invalidType = true;
                                }
                                else
                                {
                                    Compiler.AddError(new InvalidTypeError(Compiler.GetLineNumber(), ValueStack[ValueStack.Depth-3].val_type, ValType.Int, ValType.Double));
                                    invalidType = true;
                                }
                            }
                            // And both are bool
                            else if(ValueStack[ValueStack.Depth-3].val_type != ValueStack[ValueStack.Depth-1].val_type)
                            {
                                Compiler.AddError(new InvalidTypeError(Compiler.GetLineNumber(), ValueStack[ValueStack.Depth-3].val_type, ValueStack[ValueStack.Depth-1].val_type));
                                invalidType = true;
                            }
                        }

                        if(!invalidType)
                        {
                            CurrentSemanticValue.val_type = ValType.Bool;
                            right = Compiler.GetNode();
                            left = Compiler.GetNode();
                            Compiler.AddNode(new BinaryOperationNode(Compiler.GetLineNumber(), CurrentSemanticValue.val_type, ValueStack[ValueStack.Depth-2].op_type, left, right)); 
                        }
                     }
#line default
        break;
      case 50: // relExp -> addExp
#line 358 "../../kompilator.y"
                    {
                        CurrentSemanticValue.val_type = ValueStack[ValueStack.Depth-1].val_type;
                    }
#line default
        break;
      case 51: // addOp -> Plus
#line 363 "../../kompilator.y"
                                      { CurrentSemanticValue.op_type = OpType.Plus; }
#line default
        break;
      case 52: // addOp -> Minus
#line 364 "../../kompilator.y"
                                      { CurrentSemanticValue.op_type = OpType.Minus; }
#line default
        break;
      case 53: // addExp -> addExp, addOp, mulExp
#line 368 "../../kompilator.y"
                    {
                        var invalidType = false;
                        if(ValueStack[ValueStack.Depth-3].val_type == ValType.Bool)
                        {
                            var error = new InvalidTypeError(Compiler.GetLineNumber(), ValueStack[ValueStack.Depth-3].val_type, ValType.Int, ValType.Double);
                            Compiler.AddError(error);
                            invalidType = true;
                        }
                        if(ValueStack[ValueStack.Depth-1].val_type == ValType.Bool)
                        {
                            var error = new InvalidTypeError(Compiler.GetLineNumber(), ValueStack[ValueStack.Depth-1].val_type, ValType.Int, ValType.Double);
                            Compiler.AddError(error);
                            invalidType = true;
                        }

                        if(invalidType)
                            CurrentSemanticValue.val_type = ValType.Int;
                        else
                            CurrentSemanticValue.val_type = ValueStack[ValueStack.Depth-3].val_type == ValType.Int ? ValueStack[ValueStack.Depth-1].val_type : ValType.Double;

                        var right = Compiler.GetNode();
                        var left = Compiler.GetNode();
                        Compiler.AddNode(new BinaryOperationNode(Compiler.GetLineNumber(), CurrentSemanticValue.val_type, ValueStack[ValueStack.Depth-2].op_type, left, right)); 
                    }
#line default
        break;
      case 54: // addExp -> mulExp
#line 393 "../../kompilator.y"
                    {
                        CurrentSemanticValue.val_type = ValueStack[ValueStack.Depth-1].val_type;
                    }
#line default
        break;
      case 55: // mulOp -> Multiply
#line 398 "../../kompilator.y"
                                        { CurrentSemanticValue.op_type = OpType.Multiply; }
#line default
        break;
      case 56: // mulOp -> Divide
#line 399 "../../kompilator.y"
                                        { CurrentSemanticValue.op_type = OpType.Divide; }
#line default
        break;
      case 57: // mulExp -> mulExp, mulOp, bitExp
#line 403 "../../kompilator.y"
                    {
                        var invalidType = false;
                        if(ValueStack[ValueStack.Depth-3].val_type == ValType.Bool)
                        {
                            var error = new InvalidTypeError(Compiler.GetLineNumber(), ValueStack[ValueStack.Depth-3].val_type, ValType.Int, ValType.Double);
                            Compiler.AddError(error);
                            invalidType = true;
                        }
                        if(ValueStack[ValueStack.Depth-1].val_type == ValType.Bool)
                        {
                            var error = new InvalidTypeError(Compiler.GetLineNumber(), ValueStack[ValueStack.Depth-1].val_type, ValType.Int, ValType.Double);
                            Compiler.AddError(error);
                            invalidType = true;
                        }

                        if(invalidType)
                            CurrentSemanticValue.val_type = ValType.Int;
                        else
                            CurrentSemanticValue.val_type = ValueStack[ValueStack.Depth-3].val_type == ValType.Int ? ValueStack[ValueStack.Depth-1].val_type : ValType.Double;

                        var right = Compiler.GetNode();
                        var left = Compiler.GetNode();
                        Compiler.AddNode(new BinaryOperationNode(Compiler.GetLineNumber(), CurrentSemanticValue.val_type, ValueStack[ValueStack.Depth-2].op_type, left, right)); 
                    }
#line default
        break;
      case 58: // mulExp -> bitExp
#line 428 "../../kompilator.y"
                    {
                        CurrentSemanticValue.val_type = ValueStack[ValueStack.Depth-1].val_type;
                    }
#line default
        break;
      case 59: // bitOp -> BitOr
#line 433 "../../kompilator.y"
                                        { CurrentSemanticValue.op_type = OpType.BitOr; }
#line default
        break;
      case 60: // bitOp -> BitAnd
#line 434 "../../kompilator.y"
                                        { CurrentSemanticValue.op_type = OpType.BitAnd; }
#line default
        break;
      case 61: // bitExp -> bitExp, bitOp, unaryExp
#line 438 "../../kompilator.y"
                    {
                        if(ValueStack[ValueStack.Depth-3].val_type != ValType.Int && ValueStack[ValueStack.Depth-3].val_type != ValType.Dynamic)
                        {
                            var error = new InvalidTypeError(Compiler.GetLineNumber(), ValueStack[ValueStack.Depth-3].val_type, ValType.Int);
                            Compiler.AddError(error);
                        }
                        if(ValueStack[ValueStack.Depth-1].val_type != ValType.Int && ValueStack[ValueStack.Depth-3].val_type != ValType.Dynamic)
                        {
                            var error = new InvalidTypeError(Compiler.GetLineNumber(), ValueStack[ValueStack.Depth-1].val_type, ValType.Int);
                            Compiler.AddError(error);
                        }

                        CurrentSemanticValue.val_type = ValType.Int;
                        
                        var right = Compiler.GetNode();
                        var left = Compiler.GetNode();
                        Compiler.AddNode(new BinaryOperationNode(Compiler.GetLineNumber(), CurrentSemanticValue.val_type, ValueStack[ValueStack.Depth-2].op_type, left, right)); 
                    }
#line default
        break;
      case 62: // bitExp -> unaryExp
#line 457 "../../kompilator.y"
                    {
                        CurrentSemanticValue.val_type = ValueStack[ValueStack.Depth-1].val_type;
                    }
#line default
        break;
      case 63: // unaryExp -> term
#line 463 "../../kompilator.y"
                    { 
                        CurrentSemanticValue.val_type = ValueStack[ValueStack.Depth-1].val_type; 
                    }
#line default
        break;
      case 64: // unaryExp -> Minus, unaryExp
#line 467 "../../kompilator.y"
                    { 
                        if(ValueStack[ValueStack.Depth-1].val_type == ValType.Bool)
                        {
                            var error = new InvalidTypeError(Compiler.GetLineNumber(), ValueStack[ValueStack.Depth-1].val_type, ValType.Int, ValType.Double);
                            Compiler.AddError(error);
                        }

                        CurrentSemanticValue.val_type = ValueStack[ValueStack.Depth-1].val_type;

                        var child = Compiler.GetNode();
                        Compiler.AddNode(new UnaryOperationNode(Compiler.GetLineNumber(), CurrentSemanticValue.val_type, OpType.Minus, child)); 
                    }
#line default
        break;
      case 65: // unaryExp -> BitNot, unaryExp
#line 480 "../../kompilator.y"
                    { 
                        if(ValueStack[ValueStack.Depth-1].val_type == ValType.Double || ValueStack[ValueStack.Depth-1].val_type == ValType.Bool)
                        {
                            var error = new InvalidTypeError(Compiler.GetLineNumber(), ValueStack[ValueStack.Depth-1].val_type, ValType.Int);
                            Compiler.AddError(error);
                        }

                        CurrentSemanticValue.val_type = ValueStack[ValueStack.Depth-1].val_type;

                        var child = Compiler.GetNode();
                        Compiler.AddNode(new UnaryOperationNode(Compiler.GetLineNumber(), CurrentSemanticValue.val_type, OpType.BitNot, child)); 
                    }
#line default
        break;
      case 66: // unaryExp -> LogNot, unaryExp
#line 493 "../../kompilator.y"
                    {
                        if(ValueStack[ValueStack.Depth-1].val_type == ValType.Int || ValueStack[ValueStack.Depth-1].val_type == ValType.Double)
                        {
                            var error = new InvalidTypeError(Compiler.GetLineNumber(), ValueStack[ValueStack.Depth-1].val_type, ValType.Bool);
                            Compiler.AddError(error);
                        }

                        CurrentSemanticValue.val_type = ValueStack[ValueStack.Depth-1].val_type;

                        var child = Compiler.GetNode();
                        Compiler.AddNode(new UnaryOperationNode(Compiler.GetLineNumber(), CurrentSemanticValue.val_type, OpType.LogNot, child)); 
                    }
#line default
        break;
      case 67: // unaryExp -> OpenPar, Int, ClosePar, unaryExp
#line 506 "../../kompilator.y"
                    {
                        CurrentSemanticValue.val_type = ValType.Int;

                        var child = Compiler.GetNode();
                        Compiler.AddNode(new UnaryOperationNode(Compiler.GetLineNumber(), CurrentSemanticValue.val_type, OpType.IntCast, child)); 
                    }
#line default
        break;
      case 68: // unaryExp -> OpenPar, Double, ClosePar, unaryExp
#line 513 "../../kompilator.y"
                    {
                        CurrentSemanticValue.val_type = ValType.Double;

                        var child = Compiler.GetNode();
                        Compiler.AddNode(new UnaryOperationNode(Compiler.GetLineNumber(), CurrentSemanticValue.val_type, OpType.DoubleCast, child)); 
                    }
#line default
        break;
      case 69: // term -> Ident
#line 522 "../../kompilator.y"
                    {
                        // Throw if variable not declared, else get ValueType
                        var varType =  Compiler.GetVariable(ValueStack[ValueStack.Depth-1].s_val);
                        if(varType == null)
                        {
                            var error = new VariableNotDeclaredError(Compiler.GetLineNumber(), ValueStack[ValueStack.Depth-1].s_val);
                            Compiler.AddError(error);

                            varType = ValType.Dynamic;
                        }

                        CurrentSemanticValue.val_type = varType.Value;
                        Compiler.AddNode(new VariableNode(Compiler.GetLineNumber(), CurrentSemanticValue.val_type, ValueStack[ValueStack.Depth-1].s_val)); 
                    }
#line default
        break;
      case 70: // term -> const
#line 537 "../../kompilator.y"
                    { 
                        CurrentSemanticValue.val_type = ValueStack[ValueStack.Depth-1].val_type;
                    }
#line default
        break;
      case 71: // term -> OpenPar, exp, ClosePar
#line 541 "../../kompilator.y"
                    {
                        CurrentSemanticValue.val_type = ValueStack[ValueStack.Depth-2].val_type;
                    }
#line default
        break;
      case 72: // const -> IntValue
#line 547 "../../kompilator.y"
                    {
                        CurrentSemanticValue.val_type = ValType.Int;
                        Compiler.AddNode(new ConstantNode(Compiler.GetLineNumber(), CurrentSemanticValue.val_type, ValueStack[ValueStack.Depth-1].i_val)); 
                    }
#line default
        break;
      case 73: // const -> DoubleValue
#line 552 "../../kompilator.y"
                    { 
                        CurrentSemanticValue.val_type = ValType.Double;
                        Compiler.AddNode(new ConstantNode(Compiler.GetLineNumber(), CurrentSemanticValue.val_type, ValueStack[ValueStack.Depth-1].d_val)); 
                    }
#line default
        break;
      case 74: // const -> BoolValue
#line 557 "../../kompilator.y"
                    { 
                        CurrentSemanticValue.val_type = ValType.Bool;
                        Compiler.AddNode(new ConstantNode(Compiler.GetLineNumber(), CurrentSemanticValue.val_type, ValueStack[ValueStack.Depth-1].b_val)); 
                    }
#line default
        break;
    }
#pragma warning restore 162, 1522
  }

  protected override string TerminalToString(int terminal)
  {
    if (aliases != null && aliases.ContainsKey(terminal))
        return aliases[terminal];
    else if (((Tokens)terminal).ToString() != terminal.ToString(CultureInfo.InvariantCulture))
        return ((Tokens)terminal).ToString();
    else
        return CharToString((char)terminal);
  }

#line 564 "../../kompilator.y"
public Parser(Scanner scanner) : base(scanner) { }
#line default
}
}
